image: debian/stable
oauth: pages.sr.ht/PAGES:RW
environment:
  site: xhtml.club
sources:
  - https://git.sr.ht/~bt/xhtml-club
tasks:
- package: |
    cd xhtml-club
    tar -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
