image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- go
- hut
environment:
site: xhtml.club
sources:
- https://git.sr.ht/~bt/xhtml-club
tasks:
- package: |
    cd xhtml-club
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d xhtml.club site.tar.gz